### GET all weapons
GET http://localhost:9080/jakarta-lab-app-1.0/api/weapons

### GET not existing weapon
GET http://localhost:9080/jakarta-lab-app-1.0/api/weapons/245e4fd0-6f4c-4f33-a2b1-81095eba093c

### GET existing weapon
GET http://localhost:9080/jakarta-lab-app-1.0/api/weapons/a1e77f04-e157-470e-b775-097eb45f4139


### PUT new weapon
PUT http://localhost:9080/jakarta-lab-app-1.0/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Content-Type: application/json

{
  "name": "Bow of The Shadows",
  "damage": "95",
  "weight": "6",
  "value": "1900",
  "weaponType": "cdfbd2ad-7c1e-48d7-9f91-2d6d0c089b60",
  "player": "665e4aba-0640-49c2-b71f-4ddf1f9674ba"
}

### GET created weapon
GET http://localhost:9080/jakarta-lab-app-1.0/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b

### PATCH new weapon
PATCH http://localhost:9080/jakarta-lab-app-1.0/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Content-Type: application/json

{
  "name": "Damaged Bow of The Shadows",
  "damage": "70",
  "weight": "3",
  "value": "1500"
}

### GET patched weapon
GET http://localhost:9080/jakarta-lab-app-1.0/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b

### GET all weapons of a player
GET http://localhost:9080/jakarta-lab-app-1.0/api/players/665e4aba-0640-49c2-b71f-4ddf1f9674ba/weapons

### GET all weapons of a weapon type
GET http://localhost:9080/jakarta-lab-app-1.0/api/weapontypes/cdfbd2ad-7c1e-48d7-9f91-2d6d0c089b60/weapons


///
### CHECK CASCADE DELETION OF ELEMENTS WHEN DELETING CATEGORY
DELETE http://localhost:9080/jakarta-lab-app-1.0/api/weapontypes/cdfbd2ad-7c1e-48d7-9f91-2d6d0c089b60

### GET all weapons
GET http://localhost:9080/jakarta-lab-app-1.0/api/weapons
///