### GET all weapontypes
GET http://localhost:9080/jakarta-lab-app/api/weapontypes

### GET not existing weapontype
GET http://localhost:9080/jakarta-lab-app/api/weapontypes/f073a31e-3723-4b70-8678-059fa5fa2ecd

### GET existing weapontype
GET http://localhost:9080/jakarta-lab-app/api/weapontypes/ef47b366-7352-417f-a232-c530e65d7226


### PUT new weapontype
PUT http://localhost:9080/jakarta-lab-app/api/weapontypes/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Content-Type: application/json

{
  "name": "One Handed Sword",
  "speed": "3.4",
  "isTwoHanded": "false",
  "damageType": "PHYSICAL"
}

### GET created weapontype
GET http://localhost:9080/jakarta-lab-app/api/weapontypes/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05

### PATCH new weapontype
PATCH http://localhost:9080/jakarta-lab-app/api/weapontypes/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Content-Type: application/json

{
  "name": "Short Sword",
  "speed": "3.2",
  "isTwoHanded": "false",
  "damageType": "PHYSICAL"
}

### GET patched weapontype
GET http://localhost:9080/jakarta-lab-app/api/weapontypes/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05

### DELETE WEAPON TYPE
DELETE http://localhost:9080/jakarta-lab-app/api/weapontypes/cdfbd2ad-7c1e-48d7-9f91-2d6d0c089b60